# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/bump.yaml
---
name: bump

on:
  release:
    types:  # This triggers when a release is published, or a pre-release is changed to a release
      - released
  # workflow_dispatch will let us manually trigger the workflow from GitHub actions dashboard.
  # See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  deploy:
    name: "netlify/deploy"
    runs-on: ubuntu-20.04  # Hard-coding an LTS means maintenance, but only once each 2 years!
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install netlify-cli"
        run: npm install --save-dev netlify-cli

      - name: "Trigger Netlify deploy"
        run: ./node_modules/.bin/netlify deploy --message="deploy ${TAG}" --trigger --auth=${NETLIFY_AUTH_TOKEN} --site=${NETLIFY_SITE_ID}
        env: # https://github.com/tetratelabs/archive-envoy/settings/secrets
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # https://app.netlify.com/user/applications/personal
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # .netlify/state.json/siteId
